#!/bin/bash

data=`mktemp`

grep -a Open "$1" | awk '{print NR,$4}'> $data

max=`cat $data | cut -d ' ' -f 1 | sort -n | tail -1`
min=`cat $data | cut -d ' ' -f 1 | sort -n | head -1`
num=`cat $data| wc -l`

echo $num $min $max

ratio=`echo "scale=4;($max-$min)/$num" | bc`

cat $data | gnuplot -e "set terminal pdf; set size ratio $ratio; set style line 1 lc rgb 'red' pt 7 ps 0.01; plot '/dev/stdin' with points ls 1" > "$2"
