#!/bin/bash

out_dir="/scratch/network/yarmola/marg_sym_param/batch"
words="/u/yarmola/margsym/margulis-search/words"
impossible="/u/yarmola/margsym/margulis-search/impossible"
bad_relators="/u/yarmola/margsym/margulis-search/bad_relators"

m_bnd="1.38"
r_bnd="1.999"

while read t
do
  key=$(echo "$t" | cut -d ':' -f1)
  b=$(echo "$t" | cut -d ':' -f2)
  echo $key $b
  echo $key | /u/yarmola/margsym/margulis-search/bin/refine_marg --fill_holes --box "$b" --max_depth 150 --truncate_depth 6 --invent_depth 70 --max_size 3000000 --words "$words" --word_search_depth 6 -m $m_bnd -r $r_bnd --impossible "$impossible" --bad_relators "$bad_relators" > "$out_dir/${b}.out" 2> "$out_dir/${b}.err"
done
