#!/bin/bash

data_dir="refine_census"
name="box"

if [ ! -d "$data_dir" ]; then
    mkdir "$data_dir"
fi

if [[ $# > 0 ]]; then
    box="$1"
fi

if [[ $# > 1 ]]; then
    name="$1"
    box="$2"
fi

echo '1' | ../bin/refine_new --box "$box" --max_depth 300 --truncate_depth 6 --invent_depth 36 --max_size 3000000 --words ../words --word_search_depth 6 --powers none > "$data_dir/$name.out" 2> "$data_dir/$name.err"
