#!/bin/bash

data_dir="refine_census"
name="box"

if [ ! -d "$data_dir" ]; then
    mkdir "$data_dir"
fi

if [[ $# > 0 ]]; then
    box="$1"
fi

if [[ $# > 1 ]]; then
    name="$1"
    box="$2"
fi

echo 0 | ../bin/refine_marg_debug --box "$box" --max_depth 150 --truncate_depth 6 --invent_depth 18 --max_size 3000000 --words ../words_all --word_search_depth -1 --powers none > "$data_dir/$name.out" 2> "$data_dir/$name.err"
