#!/bin/bash

data_dir="refine_census"
name="box"

if [ ! -d "$data_dir" ]; then
    mkdir "$data_dir"
fi

if [[ $# > 0 ]]; then
    box="$1"
    #name="$1"
fi

if [[ $# > 1 ]]; then
    name="$1"
    box="$2"
fi

test="5"
#test="A(yXyXXYY,)"

echo $test | ../bin/refine_marg --box "$box" --max_depth 150 --truncate_depth 18 --invent_depth 52 --max_size 3000000 --words ../words_none --word_search_depth 6 -m 1.8 -r 1.6153 --powers none > "$data_dir/$name.out" 2> "$data_dir/$name.err"
