#include "RelatorTest.hh"
#include "types.hh"
#include <cstdio>

using namespace std;

set<string> sym_manifold_rels = {
  "XXyyXXYXY",
  "YXYxYYxYX",
  "xxyyxxYxY",
  "yxyyxyXyX"
};

set<string> sym_manifold_rels_old = {
    "XXYXyXyXY",
    "XXYYXXyXy",
    "XXYYxYxYY",
    "XXyyXXYXY",
    "XyXyXYXXY",
    "XyxyyxyXy",
    "XyyxxyyXy",
    "YXYxYYxYX",
    "YxYXYXYxY",
    "xYxyxxyxY",
    "xxYxyxyxY",
    "xxyyxxYxY",
    "yxyyxyXyX",
    "XXYXyXyXY",
    "XXYYXXyXy",
    "XXYYxYxYY",
    "XXyyXXYXY",
    "XyXyXYXXY",
    "XyxyyxyXy",
    "XyyxxyyXy",
    "YXYxYYxYX",
    "YxYXYXYxY",
    "xYxyxxyxY",
    "xxYxyxyxY",
    "xxyyxxYxY",
    "yxyyxyXyX",
    "XYxYXyXyyyyyyyXy",
    "XXXXXYYXXYYYXXYY",
    "XXXyyXXyyyyyXXyy",
    "XXXYYXXYYYYYXXYY",
    "XYXYXYXyxYXYXYxy",
    "XXXyyyXXYYXXyyy",
    "XXXyyxxyyXXXyyy",
    "XXXYYYxxYYxxYYY",
    "XXXYYYXXyyXXYYY",
    "XXXyXXXyXXYYXXy",
    "XYxYYYYYYYYxYXy",
    "XXXXXXXYXYxyxYXY",
    "XXXYYxxyyyyyxxYY",
    "XXXXXyyxxYYYxxyy",
    "XXXyyXXXyyyxyyy",
    "XXXYXXXYYYxxYYY",
    "XXXYYYXYYYXXXyy",
    "XXXXXyyXXyyyXXyy",
    "XXXYYXXYYXXXyyy",
    "XXXYYYXXXYYxxYY",
    "XXyyxyyyxyyyxyy",
    "XXXXXyyyyXYXyyyy",
    "XXXXXXXyXyxYxyXy",
    "XXXYYXXXyyyXyyy",
    "XXXXXXYXYYYYYXY",
    "XXXYYXXXYYYxYYY",
    "XXXYXXXyyyXXyyy",
    "XXXyXXXyyyxxyyy",
    "XXYYxYYYxYYYxYY",
    "XYxYxYxYXyxYxYxy",
    "XYXYXYxyXYXYXyxY",
    "XXYXYXYXXYYXYXYY",
    "XXXXXXXyxyXYXyxy",
    "XYXyxyXYXyyyyyy",
    "XXXXXXyxyXYXyxy",
    "XXXXXXYxYXyXYxY",
    "XXYxyXYXYXYXyxY",
    "XXYXYXYXXYxyyxY",
    "XXyXyXyXXyxYYxy",
    "XYxYxYxYXyxYYxy",
    "XXyxYXyXyXyXYxy",
    "XXYxyyxyxyxyyxY",
    "XXyxYYxYxYxYYxy",
    "XYXYXYxyXYYXyxY",
    "XXyxYxyXyXyxYxy",
    "XYxYXyXyXYxYXyy",
    "XYXYXyxyXYYXyxy",
    "XYxYYxYXyxYxYxy",
    "XXYXyxYXYXYxyXY",
    "XYXYXyxYXYYXYxy",
    "XXXyyyxxyyxxyyy",
    "XXXXYYYYXyXYYYY",
    "XXXXyxyXXXXyyyy",
    "XXXXYYYYXXXXYxY",
    "XXXXyyyyXYXyyyy",
    "XXXXyyyyxyxyyyy",
    "XXXXYYYYxYxYYYY",
    "XXXXYXYXXXXyyyy",
    "XXXXYYYYXXXXyXy",
    "XXyXyXyXXyyXyXyy",
    "XXyXyXXyyXyXyXyy",
    "XXYXYXXYYXYXYXYY",
    "XXXXyXXXYYYXXXy",
    "XXXyyyxyyyyxyyy",
    "XXXYYYxYYYYxYYY",
    "XXXXYXXXyyyXXXY",
    "XXYXXyyXyyXyyXyy",
    "XXYXXYXXYXXYYxYY",
    "XXXXyxyXXXXyyyyy",
    "XXXXXYYYYXyXYYYY",
    "XXyXXyXXyXXyyxyy",
    "XXYYXYYXYYXYYXXy",
    "XYXyxyXYXyyyyyyy",
    "XXXXXXXXXYxyXyxY",
    "XXXXXXYxyyyyyxY",
    "XYxYYYYYYYYYxYXy",
    "XXXXXXXXXYXyxyXY",
    "XXXXXXXXYXyxyXY",
    "XYXyxyyyyyyyyxy",
    "XYXyxYYYYYYYYYxy",
    "XYYYYYYYYYXyxYxy",
    "XXXXXXXXyXYxYXy",
    "XYYYYYYXyXYxYXy",
    "XXXXXYxyyyyyyxY",
    "XXXXXXyXyyyyyXy",
    "XXXXXYXYYYYYYXY",
    "XXXXXXXXXyxYXYxy",
    "XXXXXyxYYYYYYxy",
    "XXXXXXXXyxYXYxy",
    "XXXXXXXXYxyXyxY",
    "XXXXXXyxYYYYYxy",
    "XYXyxYYYYYYYYxy",
    "XYYYYYYYYXyxYxy",
    "XXXXXyXyyyyyyXy",
    "XXXXXXXXXyXYxYXy",
    "XXXXXXXYxYXyXYxY",
    "XYYYYYYYXyXYxYXy",
    "XYXYYYYYYYXYXyxy",
    "XXXyyxxYYYYYxxyy",
    "XYXyyXYXyyXYXyyy",
    "XYYXyXYYXyXYYYXy",
    "XXXyxyXXyxyXXyxy",
    "XYXYxyyxYXYxyyxY",
    "XYxYXyyXYxYxYXyy",
    "XXyyXyXyyXXyyXyy",
    "XXXXXYYXXYYXXYY",
    "XXyyXXyyXXyyyyy",
    "XXXXXyyxxyyxxyy",
    "XXYYXXYYXXyyyyy",
    "XXYYXYXYYXXYYXYY",
    "XXYYYYYXXyyXXyy",
    "XXYXXYXXyXyXy",
    "XXYXXyyXyy",
    "XXyxYxyXXyxy",
    "XXYYxYYXXyyy",
    "XYXYXYxYxYxY",
    "XYXYYxYxYY",
    "XXXyyXXyXXyy",
    "XYXyxyXYXyyy",
    "XYYXyXYYXyxy",
    "XXyXyXXyyXyy",
    "XXyXXyyXyXyy",
    "XYYXYYXYxYxY",
    "XXXYXXXyyXXyy",
    "XXXYYXXYYXXXy",
    "XYYXYYxYxYxYY",
    "XXYXYXYXXyXXy",
    "XYYYYXyXYxYXy",
    "XXyXXyyyXXyyy",
    "XXYXYXXyXyXy",
    "XXYXXYYxYY",
    "XXXyxYXYxy",
    "XXXyyXXXyyXyy",
    "XXXYYXXYXXYY",
    "XXyXXyyxyy",
    "XYXyxyXYYXyxy",
    "XXyxyXXyyXXyy",
    "XXyyXyyXXyyy",
    "XYXYXYXyXyXy",
    "XXYXXyyXXyy",
    "XXyyXXyyxyy",
    "XXXyyxxyyxxyy",
    "XYYYXyXYxYXy",
    "XXYYXXYYYxYYY",
    "XXYYXXYxYxYxY",
    "XXXYYXXXyXy",
    "XXXYXXyyXXY",
    "XXYXYXXyXXy",
    "XXYXXyyXyyXyy",
    "XXYXXYXXYYxYY",
    "XXYXXYYYXXYYY",
    "XXyxyXXyyy",
    "XXXYYXyXYY",
    "XXYYYXXYxY",
    "XXXXXyXyyyyXy",
    "XXXYYYXXXYxY",
    "XXYYxYYYxYY",
    "XYXyxyXYXyyyy",
    "XXXXyxyXYXyxy",
    "XYxYXyXYxYXyy",
    "XXXYYxxYYxxYY",
    "XXyyyxyxyyy",
    "XXXYXYXYXXXyy",
    "XXXXXXyXYxYXy",
    "XYXyyXYxYXyy",
    "XXXYxyXyxY",
    "XXXYYXXXYYXYY",
    "XXXyxyXYXyxy",
    "XYXYxyXYXyxY",
    "XYxYxYXyxYxy",
    "XXXYxYXyXYxY",
    "XYxYXyxYxYxy",
    "XXXyxyXXXyyy",
    "XYXYXyxYXYxy",
    "XXyXXyyXyyXyy",
    "XXyXXyXXyyXyy",
    "XXYXXYYXYYXYY",
    "XXYXXYXXYYXYY",
    "XXYXXYXXyXyXy",
    "XXYXXyyXyy",
    "XXyxYxyXXyxy",
    "XXYYxYYXXyyy",
    "XYXYXYxYxYxY",
    "XYXYYxYxYY",
    "XXXyyXXyXXyy",
    "XYXyxyXYXyyy",
    "XYYXyXYYXyxy",
    "XXyXyXXyyXyy",
    "XXyXXyyXyXyy",
    "XXYYXyXyXYY",
    "XYYXYYXYxYxY",
    "XXXYXXXyyXXyy",
    "XXXYYXXYYXXXy",
    "XXXyXXyXXXyyy",
    "XYYXYYxYxYxYY",
    "XXYXYXYXXyXXy",
    "XXyXyyxyxyyXy",
    "XYYYYXyXYxYXy",
    "XXyyXyxyxyXyy",
    "XXyXXyyyXXyyy",
    "XXYXYXXyXyXy",
    "XXYXXYYxYY",
    "XXXyxYXYxy",
    "XXXyyXXXyyXyy",
    "XXXYYXXYXXYY",
    "XXyXXyyxyy",
    "XYXyxyXYYXyxy",
    "XXyxyXXyyXXyy",
    "XXyyXyyXXyyy",
    "XXXyxYYxYYxy",
    "XYXYXYXyXyXy",
    "XXYXXyyXXyy",
    "XXyyXXyyxyy",
    "XXYxYXXYxyyxY",
    "XXyxYYxyXXyxy",
    "XXXyyxxyyxxyy",
    "XYYYXyXYxYXy",
    "XXYYXXYYYxYYY",
    "XXYYXXYxYxYxY",
    "XXXYYXXXyXy",
    "XXXYXXyyXXY",
    "XXYXYXXyXXy",
    "XXYXXyyXyyXyy",
    "XXYXXYXXYYxYY",
    "XXYXXYYYXXYYY",
    "XXyxyXXyyy",
    "XXXYYXyXYY",
    "XXYYYXXYxY",
    "XXXXXyXyyyyXy",
    "XXXYYYXXXYxY",
    "XXYYxYYYxYY",
    "XYXyxyXYXyyyy",
    "XXXXyxyXYXyxy",
    "XYxYXyXYxYXyy",
    "XXYxyyxYxyyxY",
    "XXXYYxxYYxxYY",
    "XXyyyxyxyyy",
    "XXXYXYXYXXXyy",
    "XXXXXXyXYxYXy",
    "XYXyyXYxYXyy",
    "XXXYxyyxyyxY",
    "XXXYxyXyxY",
    "XXYXXYxyyyxY",
    "XXXYYXXXYYXYY",
    "XXXyxyXYXyxy",
    "XYXYxyXYXyxY",
    "XYxYxYXyxYxy",
    "XXXYxYXyXYxY",
    "XYxYXyxYxYxy",
    "XXXyxyXXXyyy",
    "XYXYXyxYXYxy",
    "XXyXXyyXyyXyy",
    "XXyXXyXXyyXyy",
    "XXYXXYYXYYXYY",
    "XXYXXYXXYYXYY",
    "XXXXYXYYYYYXY",
    "XXXXXXyxYXYxy",
    "XXXXXXYxyXyxY",
    "XXyxYYxYxYYxy",
    "XXYXYXXYxyyxY",
    "XXYxyyxyxyyxY",
    "XXyxYXyXyXYxy",
    "XYXYxyXYYXyxY",
    "XXYxyXYXYXyxY",
    "XYxYxYXyxYYxy",
    "XXyXyXXyxYYxy",
    "XXXYYXyxxyXYY",
    "XXXyyXYxxYXyy",
    "XXYYYXXYxyyxY",
    "XXyxYYxyXXyyy",
    "XXXyxYXyyXYxy",
    "XXYxyXYYYXyxY",
    "XXXYxyXYYXyxY",
    "XXyxYXyyyXYxy",
    "XXYYxYxYY",
    "XYXYxYYxY",
    "XXYXYXXyy",
    "XXyyxyxyy",
    "XXyXYXYXy",
    "XXYXyXyXY",
    "XYYXYxYxY",
    "XXYYXXyXy",
    "XXXYxyyxY",
    "XYYXyxYxy",
    "XXyxYYYxy",
    "XXXyxYYxy",
    "XXyxYXYxy",
    "XXYxyyyxY",
    "XXYxyXyxY",
    "XYXyxYYxy",
    "XXXYYYXyXYYY",
    "XXXyyyXYXyyy",
    "XXyyXXyyyxyyy",
    "XXYYXXYYxYxYY",
    "XXYXYXXyyXXyy",
    "XXyyXXyyxyxyy",
    "XXYYXXYYXXyXy",
    "XXyxYxyXyxYxy",
    "XXyxyxyXXyy",
    "XXYYXXYxYxY",
    "XXyyXYXYXyy",
    "XXYXyxyXYXXYY",
    "XXyyXyxYxyXyy",
    "XXYYXYxyxYXYY",
    "XXyXYxYXyXXyy",
    "XXYXyXyxyXyXY",
    "XYXyXyxyyxyXy",
    "XXyXYXYxYXYXy",
    "XYXYxYYxYXYXy",
    "XYYYXyxYxy",
    "XYXyxYYYxy",
    "XXYXXYYXYXYY",
    "XXYXYXXYYXYY",
    "XYXyxyyyyyxy",
    "XXXXXyXYxYXy",
    "XXXXXYXyxyXY",
    "XYxYYYYYxYXy",
    "XXXYYYxYxYYY",
    "XXXYXYXXXyyy",
    "XXXyyyxyxyyy",
    "XXYXXYXyXyXY",
    "XXyXXyXYXYXy",
    "XXXYYYXXXyXy",
    "XYXYxYYxYYxY",
    "XXYYXYYXXy",
    "XXXyyXYXyy",
    "XXXYXXYXXXYYY",
    "XXXyyyXyyXyyy",
    "XXXYYYXYYXYYY",
    "XYXYYxYYxYY",
    "XXYXXYXXyXy",
    "XXXYXYXXXyy",
    "XXYYYxYxYYY",
    "XYYXYYxYxYY",
    "XXYYYxYxYxYYY",
    "XXyyyxyxyxyyy",
    "XXXYYXXXyXyXy",
    "XYXYXYYxYYxYY",
    "XXyyxyyyxyy",
    "XXXyXXYYXXy",
    "XXYYXyXyXyXYY",
    "XYXYXYXyXyyXy",
    "XXyxyxyxyXXyy",
    "XXYXYxYxYxYXY",
    "XXyyXYXYXYXyy",
    "XXyXyxyxyxyXy",
    "XYXYYXYXyXyXy",
    "XXXXXXYXyxyXY",
    "XYXyxyyyyyyxy",
    "XYxYYYYYYxYXy",
    "XXXYxyyyyxY",
    "XXXXyxYXYxy",
    "XXXXYxyXyxY",
    "XYXyxYYYYxy",
    "XYYYYXyxYxy",
    "XXYXYXXyXyyXy",
    "XXYXYYXYXXyXy",
    "XXYYXYxYxYXYY",
    "XXYXYYxYxYYXY",
    "XXyXYXYXyXXyy",
    "XXYXyXyXYXXYY",
    "XXXXYxYXyXYxY",
    "XXYXyxYXYxyXY",
    "XXyXYxyXyxYXy",
    "XYXyxYYYYYxy",
    "XYYYYYXyxYxy",
    "XXXXXyxYXYxy",
    "XXXXXYxyXyxY",
    "XXXyxyXXXyyyy",
    "XXXXyyyXYXyyy",
    "XXXXYYYXyXYYY",
    "XXXYYYYXXXYxY",
    "XXyXXyXXyyxyy",
    "XXYYXYYXYYXXy",
    "XXYxYXXYxyxY",
    "XXXyyxxYxxyy",
    "XXYYYXXyyxyy",
    "XXXYYxxyxxYY",
    "XXXYYXyXyXYY",
    "XXYYXYYXXyXy",
    "XXYXYXXyyXyy",
    "XXyxyxyXXyyy",
    "XXYYYXXYxYxY",
    "XXYXXYYxYxYY",
    "XXyXXyyxyxyy",
    "XXXyyXYXYXyy",
    "XXyXXyxYYYxy",
    "XXXYXYYxxYYXY",
    "XXXyXyyxxyyXy",
    "XXYXYYYXYXXyy",
    "XXYYXXyXyyyXy",
    "XXYYXXYxYXYxY",
    "XXyxyXyxyXXyy",
    "XXyyXYXyXYXyy",
    "XXYYXyXYXyXYY",
    "XYYYYYYXyxYxy",
    "XXXXYxyyyyyxY",
    "XXXXXyxYYYYxy",
    "XXXXXYxyyyyxY",
    "XXXYxYxyyxYxY",
    "XXyxyxYYYxyxy",
    "XXXXyXyyyyyXy",
    "XXXyxYYYYxy",
    "XXXXYxyyyxY",
    "XXXXyxYYYxy",
    "XXXXXYXYYYYXY",
    "XXXXyxYYYYYxy",
    "XXyyXXyyXYXyy",
    "XXYxYxyyyxYxY",
    "XYXyxYXYYXYxy",
    "XYxYYxYXyxYxy",
    "XXXyxyxYYxyxy",
    "XYXyXYXyXYXyy",
    "XXYYXXYYXXYYY",
    "XXXYYXXYYXXYY",
    "XXyxyXyxyXyxy",
    "XXYxYXYxYXYxY",
    "XXyyXXyyXXyyy",
    "XXYYXXYYXyXYY",
    "XXYYXXYYXXYxY",
    "XXXyyXXyyXXyy",
    "XYXyXYXyXYYXy",
    "XXYxyxYXYxyxY",
    "XXYYXXYYxYY",
    "XYYXyxYXyXYxy",
    "XYXyxYXyyXYxy",
    "XXYxyXYxYXyxY",
    "XXYYXXYYXXy",
    "XXYXXyyxyyxyy",
    "XXYYxYYxYYXXy",
    "XXYYxYYXXyXXy",
    "XXYXXYXXyyxyy",
    "XXYYYXXyyXXyy",
    "XXyxYYxyxYYxy",
    "XXyxYXyxyXYxy",
    "XXYYXXYYXXyyy",
    "XXYYXYYXXYYY",
    "XXYXYXXyXy",
    "XYXYXYYxYxYY",
    "XYXYYxYxYxYY",
    "XXYXYXYXXyXy",
    "XYXyxYYYYYYxy",
    "yxYxxYxyXYxYX",
    "XYxYYxYXyxYxy",
    "yxyXYxyxxyxYX",
    "XYXyxYXYYXYxy",
    "XXyXYxyXyxYXy",
    "yyXyxYXyXYxyX",
    "XXYXyxYXYxyXY",
    "yyxyXYxyxYXyx"
};

bool RelatorTest::is_good(string word)
{
  if (word.length() == 0 ||
      bad_relators.find(word) != bad_relators.end() ||
      bad_relators.find(canonical_name.get_canonical_name(word)) != bad_relators.end()) {
    return false;
  }
  return true;
}

bool RelatorTest::is_sym(string word)
{
  for(auto sym_rel: sym_manifold_rels) { 
    if (canonical_name.get_canonical_name(word) ==
        canonical_name.get_canonical_name(sym_rel)) {
      return true;
    }
  }
  return false;
}


bool RelatorTest::is_impossible(string word,
    vector<string>& required_non_identities)
	{
    if (word.length() == 0) {
      return false;
    }
    // fprintf(stderr, "Testing impossible %s\n", word.c_str());
    required_non_identities.clear();
    string canon = canonical_name.get_canonical_name(word);
    if (syllables(canon) < 5 ||
        always_impossible.find(word) != always_impossible.end() ||
        always_impossible.find(canon) != always_impossible.end()) {
      fprintf(stderr, "Always impossible %s and size %d\n", word.c_str(), required_non_identities.size());
      return true;
    }
    string cycle(canon);
    int rot = 1;
    // could be optimized
    while (rot != canon.length()) {
      rotate(cycle.begin(), cycle.begin() + 1, cycle.end());
      if (cycle == canon) {
        string sub = canon.substr(0, rot);
        if (syllables(canonical_name.get_canonical_name(sub)) < 5) {
          return true;
        } else {
          required_non_identities.push_back(sub);
		      return false;
        }
      }
      ++rot;
    }
		return false;
	}

void RelatorTest::load(const char* impos_path,
                       const char* bad_rel_path)
{
  char buf[1000];
  char word_buf[1000];
  FILE* fp = fopen(impos_path, "r");
  while (fp && fgets(buf, sizeof(buf), fp)) {
    if (buf[0] != '/') {
      buf[strcspn(buf, "\r\n")] = 0;
      string canon = canonical_name.get_canonical_name(string(buf));
      always_impossible.insert(buf);
      always_impossible.insert(canon);
    }
  }
  fclose(fp);
  fp = fopen(bad_rel_path, "r");
  while (fp && fgets(buf, sizeof(buf), fp)) {
    if (buf[0] != '/') {
      buf[strcspn(buf, "\r\n")] = 0;
      string canon = canonical_name.get_canonical_name(string(buf));
      bad_relators.insert(buf);
      bad_relators.insert(canon);
    }
  }
  fprintf(stderr, "Loaded %d impossible and %d bad relators\n", always_impossible.size(),  bad_relators.size());
}

RelatorTest* RelatorTest::create(const char* impos_path,
                                 const char* bad_rel_path)
{
	RelatorTest* impossible = new RelatorTest();
	impossible->load(impos_path, bad_rel_path);
	return impossible;
}
